// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Results.proto

package refdiff.core.ResultModels;

public final class ResultsOuterClass {
  private ResultsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResultsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Models.Results)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string projectName = 5;</code>
     */
    java.lang.String getProjectName();
    /**
     * <code>string projectName = 5;</code>
     */
    com.google.protobuf.ByteString
        getProjectNameBytes();

    /**
     * <code>string sha = 6;</code>
     */
    java.lang.String getSha();
    /**
     * <code>string sha = 6;</code>
     */
    com.google.protobuf.ByteString
        getShaBytes();

    /**
     * <code>repeated string truePositives = 1;</code>
     */
    java.util.List<java.lang.String>
        getTruePositivesList();
    /**
     * <code>repeated string truePositives = 1;</code>
     */
    int getTruePositivesCount();
    /**
     * <code>repeated string truePositives = 1;</code>
     */
    java.lang.String getTruePositives(int index);
    /**
     * <code>repeated string truePositives = 1;</code>
     */
    com.google.protobuf.ByteString
        getTruePositivesBytes(int index);

    /**
     * <code>repeated string trueNegatives = 4;</code>
     */
    java.util.List<java.lang.String>
        getTrueNegativesList();
    /**
     * <code>repeated string trueNegatives = 4;</code>
     */
    int getTrueNegativesCount();
    /**
     * <code>repeated string trueNegatives = 4;</code>
     */
    java.lang.String getTrueNegatives(int index);
    /**
     * <code>repeated string trueNegatives = 4;</code>
     */
    com.google.protobuf.ByteString
        getTrueNegativesBytes(int index);

    /**
     * <code>repeated string falsePositives = 2;</code>
     */
    java.util.List<java.lang.String>
        getFalsePositivesList();
    /**
     * <code>repeated string falsePositives = 2;</code>
     */
    int getFalsePositivesCount();
    /**
     * <code>repeated string falsePositives = 2;</code>
     */
    java.lang.String getFalsePositives(int index);
    /**
     * <code>repeated string falsePositives = 2;</code>
     */
    com.google.protobuf.ByteString
        getFalsePositivesBytes(int index);

    /**
     * <code>repeated string falseNegatives = 3;</code>
     */
    java.util.List<java.lang.String>
        getFalseNegativesList();
    /**
     * <code>repeated string falseNegatives = 3;</code>
     */
    int getFalseNegativesCount();
    /**
     * <code>repeated string falseNegatives = 3;</code>
     */
    java.lang.String getFalseNegatives(int index);
    /**
     * <code>repeated string falseNegatives = 3;</code>
     */
    com.google.protobuf.ByteString
        getFalseNegativesBytes(int index);
  }
  /**
   * Protobuf type {@code Models.Results}
   */
  public  static final class Results extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Models.Results)
      ResultsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Results.newBuilder() to construct.
    private Results(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Results() {
      projectName_ = "";
      sha_ = "";
      truePositives_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      trueNegatives_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      falsePositives_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      falseNegatives_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Results();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Results(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                truePositives_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              truePositives_.add(s);
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                falsePositives_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              falsePositives_.add(s);
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                falseNegatives_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              falseNegatives_.add(s);
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                trueNegatives_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              trueNegatives_.add(s);
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              projectName_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              sha_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          truePositives_ = truePositives_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          falsePositives_ = falsePositives_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000008) != 0)) {
          falseNegatives_ = falseNegatives_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          trueNegatives_ = trueNegatives_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return refdiff.core.ResultModels.ResultsOuterClass.internal_static_Models_Results_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return refdiff.core.ResultModels.ResultsOuterClass.internal_static_Models_Results_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              refdiff.core.ResultModels.ResultsOuterClass.Results.class, refdiff.core.ResultModels.ResultsOuterClass.Results.Builder.class);
    }

    public static final int PROJECTNAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object projectName_;
    /**
     * <code>string projectName = 5;</code>
     */
    public java.lang.String getProjectName() {
      java.lang.Object ref = projectName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        projectName_ = s;
        return s;
      }
    }
    /**
     * <code>string projectName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getProjectNameBytes() {
      java.lang.Object ref = projectName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        projectName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SHA_FIELD_NUMBER = 6;
    private volatile java.lang.Object sha_;
    /**
     * <code>string sha = 6;</code>
     */
    public java.lang.String getSha() {
      java.lang.Object ref = sha_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sha_ = s;
        return s;
      }
    }
    /**
     * <code>string sha = 6;</code>
     */
    public com.google.protobuf.ByteString
        getShaBytes() {
      java.lang.Object ref = sha_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sha_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRUEPOSITIVES_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList truePositives_;
    /**
     * <code>repeated string truePositives = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getTruePositivesList() {
      return truePositives_;
    }
    /**
     * <code>repeated string truePositives = 1;</code>
     */
    public int getTruePositivesCount() {
      return truePositives_.size();
    }
    /**
     * <code>repeated string truePositives = 1;</code>
     */
    public java.lang.String getTruePositives(int index) {
      return truePositives_.get(index);
    }
    /**
     * <code>repeated string truePositives = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTruePositivesBytes(int index) {
      return truePositives_.getByteString(index);
    }

    public static final int TRUENEGATIVES_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList trueNegatives_;
    /**
     * <code>repeated string trueNegatives = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getTrueNegativesList() {
      return trueNegatives_;
    }
    /**
     * <code>repeated string trueNegatives = 4;</code>
     */
    public int getTrueNegativesCount() {
      return trueNegatives_.size();
    }
    /**
     * <code>repeated string trueNegatives = 4;</code>
     */
    public java.lang.String getTrueNegatives(int index) {
      return trueNegatives_.get(index);
    }
    /**
     * <code>repeated string trueNegatives = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTrueNegativesBytes(int index) {
      return trueNegatives_.getByteString(index);
    }

    public static final int FALSEPOSITIVES_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList falsePositives_;
    /**
     * <code>repeated string falsePositives = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getFalsePositivesList() {
      return falsePositives_;
    }
    /**
     * <code>repeated string falsePositives = 2;</code>
     */
    public int getFalsePositivesCount() {
      return falsePositives_.size();
    }
    /**
     * <code>repeated string falsePositives = 2;</code>
     */
    public java.lang.String getFalsePositives(int index) {
      return falsePositives_.get(index);
    }
    /**
     * <code>repeated string falsePositives = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFalsePositivesBytes(int index) {
      return falsePositives_.getByteString(index);
    }

    public static final int FALSENEGATIVES_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList falseNegatives_;
    /**
     * <code>repeated string falseNegatives = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getFalseNegativesList() {
      return falseNegatives_;
    }
    /**
     * <code>repeated string falseNegatives = 3;</code>
     */
    public int getFalseNegativesCount() {
      return falseNegatives_.size();
    }
    /**
     * <code>repeated string falseNegatives = 3;</code>
     */
    public java.lang.String getFalseNegatives(int index) {
      return falseNegatives_.get(index);
    }
    /**
     * <code>repeated string falseNegatives = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFalseNegativesBytes(int index) {
      return falseNegatives_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < truePositives_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, truePositives_.getRaw(i));
      }
      for (int i = 0; i < falsePositives_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, falsePositives_.getRaw(i));
      }
      for (int i = 0; i < falseNegatives_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, falseNegatives_.getRaw(i));
      }
      for (int i = 0; i < trueNegatives_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, trueNegatives_.getRaw(i));
      }
      if (!getProjectNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, projectName_);
      }
      if (!getShaBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, sha_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < truePositives_.size(); i++) {
          dataSize += computeStringSizeNoTag(truePositives_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getTruePositivesList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < falsePositives_.size(); i++) {
          dataSize += computeStringSizeNoTag(falsePositives_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getFalsePositivesList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < falseNegatives_.size(); i++) {
          dataSize += computeStringSizeNoTag(falseNegatives_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getFalseNegativesList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < trueNegatives_.size(); i++) {
          dataSize += computeStringSizeNoTag(trueNegatives_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getTrueNegativesList().size();
      }
      if (!getProjectNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, projectName_);
      }
      if (!getShaBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, sha_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof refdiff.core.ResultModels.ResultsOuterClass.Results)) {
        return super.equals(obj);
      }
      refdiff.core.ResultModels.ResultsOuterClass.Results other = (refdiff.core.ResultModels.ResultsOuterClass.Results) obj;

      if (!getProjectName()
          .equals(other.getProjectName())) return false;
      if (!getSha()
          .equals(other.getSha())) return false;
      if (!getTruePositivesList()
          .equals(other.getTruePositivesList())) return false;
      if (!getTrueNegativesList()
          .equals(other.getTrueNegativesList())) return false;
      if (!getFalsePositivesList()
          .equals(other.getFalsePositivesList())) return false;
      if (!getFalseNegativesList()
          .equals(other.getFalseNegativesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PROJECTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getProjectName().hashCode();
      hash = (37 * hash) + SHA_FIELD_NUMBER;
      hash = (53 * hash) + getSha().hashCode();
      if (getTruePositivesCount() > 0) {
        hash = (37 * hash) + TRUEPOSITIVES_FIELD_NUMBER;
        hash = (53 * hash) + getTruePositivesList().hashCode();
      }
      if (getTrueNegativesCount() > 0) {
        hash = (37 * hash) + TRUENEGATIVES_FIELD_NUMBER;
        hash = (53 * hash) + getTrueNegativesList().hashCode();
      }
      if (getFalsePositivesCount() > 0) {
        hash = (37 * hash) + FALSEPOSITIVES_FIELD_NUMBER;
        hash = (53 * hash) + getFalsePositivesList().hashCode();
      }
      if (getFalseNegativesCount() > 0) {
        hash = (37 * hash) + FALSENEGATIVES_FIELD_NUMBER;
        hash = (53 * hash) + getFalseNegativesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static refdiff.core.ResultModels.ResultsOuterClass.Results parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static refdiff.core.ResultModels.ResultsOuterClass.Results parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static refdiff.core.ResultModels.ResultsOuterClass.Results parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static refdiff.core.ResultModels.ResultsOuterClass.Results parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static refdiff.core.ResultModels.ResultsOuterClass.Results parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static refdiff.core.ResultModels.ResultsOuterClass.Results parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static refdiff.core.ResultModels.ResultsOuterClass.Results parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static refdiff.core.ResultModels.ResultsOuterClass.Results parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static refdiff.core.ResultModels.ResultsOuterClass.Results parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static refdiff.core.ResultModels.ResultsOuterClass.Results parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static refdiff.core.ResultModels.ResultsOuterClass.Results parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static refdiff.core.ResultModels.ResultsOuterClass.Results parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(refdiff.core.ResultModels.ResultsOuterClass.Results prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Models.Results}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Models.Results)
        refdiff.core.ResultModels.ResultsOuterClass.ResultsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return refdiff.core.ResultModels.ResultsOuterClass.internal_static_Models_Results_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return refdiff.core.ResultModels.ResultsOuterClass.internal_static_Models_Results_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                refdiff.core.ResultModels.ResultsOuterClass.Results.class, refdiff.core.ResultModels.ResultsOuterClass.Results.Builder.class);
      }

      // Construct using refdiff.core.ResultModels.ResultsOuterClass.Results.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        projectName_ = "";

        sha_ = "";

        truePositives_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        trueNegatives_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        falsePositives_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        falseNegatives_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return refdiff.core.ResultModels.ResultsOuterClass.internal_static_Models_Results_descriptor;
      }

      @java.lang.Override
      public refdiff.core.ResultModels.ResultsOuterClass.Results getDefaultInstanceForType() {
        return refdiff.core.ResultModels.ResultsOuterClass.Results.getDefaultInstance();
      }

      @java.lang.Override
      public refdiff.core.ResultModels.ResultsOuterClass.Results build() {
        refdiff.core.ResultModels.ResultsOuterClass.Results result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public refdiff.core.ResultModels.ResultsOuterClass.Results buildPartial() {
        refdiff.core.ResultModels.ResultsOuterClass.Results result = new refdiff.core.ResultModels.ResultsOuterClass.Results(this);
        int from_bitField0_ = bitField0_;
        result.projectName_ = projectName_;
        result.sha_ = sha_;
        if (((bitField0_ & 0x00000001) != 0)) {
          truePositives_ = truePositives_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.truePositives_ = truePositives_;
        if (((bitField0_ & 0x00000002) != 0)) {
          trueNegatives_ = trueNegatives_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.trueNegatives_ = trueNegatives_;
        if (((bitField0_ & 0x00000004) != 0)) {
          falsePositives_ = falsePositives_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.falsePositives_ = falsePositives_;
        if (((bitField0_ & 0x00000008) != 0)) {
          falseNegatives_ = falseNegatives_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.falseNegatives_ = falseNegatives_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof refdiff.core.ResultModels.ResultsOuterClass.Results) {
          return mergeFrom((refdiff.core.ResultModels.ResultsOuterClass.Results)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(refdiff.core.ResultModels.ResultsOuterClass.Results other) {
        if (other == refdiff.core.ResultModels.ResultsOuterClass.Results.getDefaultInstance()) return this;
        if (!other.getProjectName().isEmpty()) {
          projectName_ = other.projectName_;
          onChanged();
        }
        if (!other.getSha().isEmpty()) {
          sha_ = other.sha_;
          onChanged();
        }
        if (!other.truePositives_.isEmpty()) {
          if (truePositives_.isEmpty()) {
            truePositives_ = other.truePositives_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTruePositivesIsMutable();
            truePositives_.addAll(other.truePositives_);
          }
          onChanged();
        }
        if (!other.trueNegatives_.isEmpty()) {
          if (trueNegatives_.isEmpty()) {
            trueNegatives_ = other.trueNegatives_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureTrueNegativesIsMutable();
            trueNegatives_.addAll(other.trueNegatives_);
          }
          onChanged();
        }
        if (!other.falsePositives_.isEmpty()) {
          if (falsePositives_.isEmpty()) {
            falsePositives_ = other.falsePositives_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureFalsePositivesIsMutable();
            falsePositives_.addAll(other.falsePositives_);
          }
          onChanged();
        }
        if (!other.falseNegatives_.isEmpty()) {
          if (falseNegatives_.isEmpty()) {
            falseNegatives_ = other.falseNegatives_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureFalseNegativesIsMutable();
            falseNegatives_.addAll(other.falseNegatives_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        refdiff.core.ResultModels.ResultsOuterClass.Results parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (refdiff.core.ResultModels.ResultsOuterClass.Results) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object projectName_ = "";
      /**
       * <code>string projectName = 5;</code>
       */
      public java.lang.String getProjectName() {
        java.lang.Object ref = projectName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          projectName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string projectName = 5;</code>
       */
      public com.google.protobuf.ByteString
          getProjectNameBytes() {
        java.lang.Object ref = projectName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          projectName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string projectName = 5;</code>
       */
      public Builder setProjectName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        projectName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string projectName = 5;</code>
       */
      public Builder clearProjectName() {
        
        projectName_ = getDefaultInstance().getProjectName();
        onChanged();
        return this;
      }
      /**
       * <code>string projectName = 5;</code>
       */
      public Builder setProjectNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        projectName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sha_ = "";
      /**
       * <code>string sha = 6;</code>
       */
      public java.lang.String getSha() {
        java.lang.Object ref = sha_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sha_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sha = 6;</code>
       */
      public com.google.protobuf.ByteString
          getShaBytes() {
        java.lang.Object ref = sha_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sha_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sha = 6;</code>
       */
      public Builder setSha(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sha_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sha = 6;</code>
       */
      public Builder clearSha() {
        
        sha_ = getDefaultInstance().getSha();
        onChanged();
        return this;
      }
      /**
       * <code>string sha = 6;</code>
       */
      public Builder setShaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sha_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList truePositives_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTruePositivesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          truePositives_ = new com.google.protobuf.LazyStringArrayList(truePositives_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string truePositives = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getTruePositivesList() {
        return truePositives_.getUnmodifiableView();
      }
      /**
       * <code>repeated string truePositives = 1;</code>
       */
      public int getTruePositivesCount() {
        return truePositives_.size();
      }
      /**
       * <code>repeated string truePositives = 1;</code>
       */
      public java.lang.String getTruePositives(int index) {
        return truePositives_.get(index);
      }
      /**
       * <code>repeated string truePositives = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTruePositivesBytes(int index) {
        return truePositives_.getByteString(index);
      }
      /**
       * <code>repeated string truePositives = 1;</code>
       */
      public Builder setTruePositives(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTruePositivesIsMutable();
        truePositives_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string truePositives = 1;</code>
       */
      public Builder addTruePositives(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTruePositivesIsMutable();
        truePositives_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string truePositives = 1;</code>
       */
      public Builder addAllTruePositives(
          java.lang.Iterable<java.lang.String> values) {
        ensureTruePositivesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, truePositives_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string truePositives = 1;</code>
       */
      public Builder clearTruePositives() {
        truePositives_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string truePositives = 1;</code>
       */
      public Builder addTruePositivesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureTruePositivesIsMutable();
        truePositives_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList trueNegatives_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTrueNegativesIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          trueNegatives_ = new com.google.protobuf.LazyStringArrayList(trueNegatives_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string trueNegatives = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getTrueNegativesList() {
        return trueNegatives_.getUnmodifiableView();
      }
      /**
       * <code>repeated string trueNegatives = 4;</code>
       */
      public int getTrueNegativesCount() {
        return trueNegatives_.size();
      }
      /**
       * <code>repeated string trueNegatives = 4;</code>
       */
      public java.lang.String getTrueNegatives(int index) {
        return trueNegatives_.get(index);
      }
      /**
       * <code>repeated string trueNegatives = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTrueNegativesBytes(int index) {
        return trueNegatives_.getByteString(index);
      }
      /**
       * <code>repeated string trueNegatives = 4;</code>
       */
      public Builder setTrueNegatives(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTrueNegativesIsMutable();
        trueNegatives_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string trueNegatives = 4;</code>
       */
      public Builder addTrueNegatives(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTrueNegativesIsMutable();
        trueNegatives_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string trueNegatives = 4;</code>
       */
      public Builder addAllTrueNegatives(
          java.lang.Iterable<java.lang.String> values) {
        ensureTrueNegativesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, trueNegatives_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string trueNegatives = 4;</code>
       */
      public Builder clearTrueNegatives() {
        trueNegatives_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string trueNegatives = 4;</code>
       */
      public Builder addTrueNegativesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureTrueNegativesIsMutable();
        trueNegatives_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList falsePositives_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFalsePositivesIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          falsePositives_ = new com.google.protobuf.LazyStringArrayList(falsePositives_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string falsePositives = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getFalsePositivesList() {
        return falsePositives_.getUnmodifiableView();
      }
      /**
       * <code>repeated string falsePositives = 2;</code>
       */
      public int getFalsePositivesCount() {
        return falsePositives_.size();
      }
      /**
       * <code>repeated string falsePositives = 2;</code>
       */
      public java.lang.String getFalsePositives(int index) {
        return falsePositives_.get(index);
      }
      /**
       * <code>repeated string falsePositives = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFalsePositivesBytes(int index) {
        return falsePositives_.getByteString(index);
      }
      /**
       * <code>repeated string falsePositives = 2;</code>
       */
      public Builder setFalsePositives(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFalsePositivesIsMutable();
        falsePositives_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string falsePositives = 2;</code>
       */
      public Builder addFalsePositives(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFalsePositivesIsMutable();
        falsePositives_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string falsePositives = 2;</code>
       */
      public Builder addAllFalsePositives(
          java.lang.Iterable<java.lang.String> values) {
        ensureFalsePositivesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, falsePositives_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string falsePositives = 2;</code>
       */
      public Builder clearFalsePositives() {
        falsePositives_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string falsePositives = 2;</code>
       */
      public Builder addFalsePositivesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureFalsePositivesIsMutable();
        falsePositives_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList falseNegatives_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFalseNegativesIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          falseNegatives_ = new com.google.protobuf.LazyStringArrayList(falseNegatives_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string falseNegatives = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getFalseNegativesList() {
        return falseNegatives_.getUnmodifiableView();
      }
      /**
       * <code>repeated string falseNegatives = 3;</code>
       */
      public int getFalseNegativesCount() {
        return falseNegatives_.size();
      }
      /**
       * <code>repeated string falseNegatives = 3;</code>
       */
      public java.lang.String getFalseNegatives(int index) {
        return falseNegatives_.get(index);
      }
      /**
       * <code>repeated string falseNegatives = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFalseNegativesBytes(int index) {
        return falseNegatives_.getByteString(index);
      }
      /**
       * <code>repeated string falseNegatives = 3;</code>
       */
      public Builder setFalseNegatives(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFalseNegativesIsMutable();
        falseNegatives_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string falseNegatives = 3;</code>
       */
      public Builder addFalseNegatives(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFalseNegativesIsMutable();
        falseNegatives_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string falseNegatives = 3;</code>
       */
      public Builder addAllFalseNegatives(
          java.lang.Iterable<java.lang.String> values) {
        ensureFalseNegativesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, falseNegatives_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string falseNegatives = 3;</code>
       */
      public Builder clearFalseNegatives() {
        falseNegatives_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string falseNegatives = 3;</code>
       */
      public Builder addFalseNegativesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureFalseNegativesIsMutable();
        falseNegatives_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Models.Results)
    }

    // @@protoc_insertion_point(class_scope:Models.Results)
    private static final refdiff.core.ResultModels.ResultsOuterClass.Results DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new refdiff.core.ResultModels.ResultsOuterClass.Results();
    }

    public static refdiff.core.ResultModels.ResultsOuterClass.Results getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Results>
        PARSER = new com.google.protobuf.AbstractParser<Results>() {
      @java.lang.Override
      public Results parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Results(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Results> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Results> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public refdiff.core.ResultModels.ResultsOuterClass.Results getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Models_Results_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Models_Results_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rResults.proto\022\006Models\"\211\001\n\007Results\022\023\n\013p" +
      "rojectName\030\005 \001(\t\022\013\n\003sha\030\006 \001(\t\022\025\n\rtruePos" +
      "itives\030\001 \003(\t\022\025\n\rtrueNegatives\030\004 \003(\t\022\026\n\016f" +
      "alsePositives\030\002 \003(\t\022\026\n\016falseNegatives\030\003 " +
      "\003(\tB\033\n\031refdiff.core.ResultModelsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Models_Results_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Models_Results_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Models_Results_descriptor,
        new java.lang.String[] { "ProjectName", "Sha", "TruePositives", "TrueNegatives", "FalsePositives", "FalseNegatives", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
